# Generated by Django 5.0.12 on 2025-10-06 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConfigurationChangeRequest', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='committee',
            old_name='administrator_nationalCode',
            new_name='administrator_nationalcode',
        ),
        migrations.AlterField(
            model_name='requesttask',
            name='status_code',
            field=models.CharField(choices=[('DEFINE', 'تعریف'), ('EXERED', 'آماده انتخاب مجری'), ('EXESEL', 'مجری انتخاب شده'), ('TESRED', 'آماده انتخاب تستر'), ('TESSEL', 'تستر انتخاب شده'), ('FINISH', 'انجام موفق'), ('FAILED', 'انجام ناموفق')], default='DEFINE', max_length=6, verbose_name='وضعیت تسک'),
        ),
        migrations.CreateModel(
            name='DataHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('modify_date', models.DateTimeField(auto_now=True, verbose_name='تاریخ آخرین تغییر')),
                ('request_changetype', models.CharField(max_length=1, verbose_name='مربوط به درخواست است یا نوع تغییر؟')),
                ('old_data', models.JSONField(null=True, verbose_name='اطلاعات قدیمی')),
                ('new_data', models.JSONField(null=True, verbose_name='اطلاعات جدید')),
                ('record_id', models.IntegerField(verbose_name='شناسه رکورد')),
                ('creator_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)ss', to='ConfigurationChangeRequest.user', verbose_name='کاربر ایجادکننده')),
                ('last_modifier_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_%(class)ss', to='ConfigurationChangeRequest.user', verbose_name='آخرین کاربر ویرایشگر')),
            ],
            options={
                'verbose_name': 'سابقه اطلاع رسانی',
                'verbose_name_plural': 'سوابق اطلاع رسانی ها',
            },
        ),
    ]
