# Generated by Django 5.0.12 on 2025-08-30 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ConfigurationChangeRequest', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userteamrole',
            name='role_title',
        ),
    ]
