# Generated by Django 5.0.12 on 2025-02-23 21:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConfigurationChangeRequest', '0002_remove_user_role_title_remove_user_team_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changetype',
            name='classification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ConfigurationChangeRequest.constvalue', verbose_name='طبقه\u200cبندی'),
        ),
        migrations.AlterField(
            model_name='configurationchangerequest',
            name='classification',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='ConfigurationChangeRequest.constvalue', verbose_name='طبقه\u200cبندی'),
        ),
        migrations.AlterField(
            model_name='configurationchangerequest',
            name='state_code',
            field=models.CharField(choices=[('DRFTD', 'پیش نویس'), ('MANAG', 'اظهار نظر مدیر مستقیم'), ('COMITE', 'اظهار نظر کمیته'), ('EXECUT', 'اجرا توسط مجری'), ('TESTER', 'تست توسط تستر'), ('FAILED', 'خاتمه ناموفقیت آمیز'), ('FINISH', 'خاتمه یافته')], default='DRFTD', help_text='لطفاً کد وضعیت را وارد کنید.', max_length=6, verbose_name='کد وضعیت'),
        ),
    ]
