# Generated by Django 5.0.12 on 2025-09-01 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConfigurationChangeRequest', '0002_remove_userteamrole_role_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='changetype',
            name='test_required',
        ),
        migrations.AlterField(
            model_name='notifygroup',
            name='team_code',
            field=models.ForeignKey(help_text='در صورتی این گروه مربوط به یک تیم است', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notify_team_code', to='ConfigurationChangeRequest.team', verbose_name='کد سمت'),
        ),
    ]
