# Generated by Django 5.0.12 on 2025-10-06 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConfigurationChangeRequest', '0002_rename_administrator_nationalcode_committee_administrator_nationalcode_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datahistory',
            options={'verbose_name': 'سابقه تغییرات رکورد', 'verbose_name_plural': 'سوابق تغییرات رکورد ها'},
        ),
        migrations.RemoveField(
            model_name='datahistory',
            name='request_changetype',
        ),
        migrations.AddField(
            model_name='datahistory',
            name='record_type',
            field=models.CharField(choices=[('R', 'درخواست'), ('C', 'نوع تغییر')], default='R', max_length=1, verbose_name='مربوط به درخواست است یا نوع تغییر؟'),
            preserve_default=False,
        ),
    ]
