# Generated by Django 5.0.12 on 2025-10-10 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ConfigurationChangeRequest', '0003_alter_datahistory_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requestextrainformation_changetype',
            old_name='change_type',
            new_name='changetype',
        ),
    ]
