# Generated by Django 5.0.12 on 2025-09-02 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConfigurationChangeRequest', '0003_remove_changetype_test_required_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configurationchangerequest',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, default='2025-09-02 12:11:10', verbose_name='تاریخ ایجاد'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='configurationchangerequest',
            name='creator_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)ss', to='ConfigurationChangeRequest.user', verbose_name='کاربر ایجادکننده'),
        ),
        migrations.AddField(
            model_name='configurationchangerequest',
            name='last_modifier_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_%(class)ss', to='ConfigurationChangeRequest.user', verbose_name='آخرین کاربر ویرایشگر'),
        ),
        migrations.AddField(
            model_name='configurationchangerequest',
            name='modify_date',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ آخرین تغییر'),
        ),
    ]
