# Generated by Django 5.0.12 on 2025-02-28 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConfigurationChangeRequest', '0003_alter_changetype_classification_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configurationchangerequest',
            name='change_type_code',
        ),
        migrations.RemoveField(
            model_name='requestteam_changetype',
            name='changetype_code',
        ),
        migrations.RemoveField(
            model_name='requestcorp_changetype',
            name='changetype_code',
        ),
        migrations.RemoveField(
            model_name='requestcorp_changetype',
            name='corp_code',
        ),
        migrations.RemoveField(
            model_name='requestteam_changetype',
            name='team_code',
        ),
        migrations.AlterField(
            model_name='configurationchangerequest',
            name='state_code',
            field=models.CharField(choices=[('DRAFTD', 'پیش نویس'), ('MANAGE', 'اظهار نظر مدیر مستقیم'), ('COMITE', 'اظهار نظر کمیته'), ('EXECUT', 'اجرا توسط مجری'), ('TESTER', 'تست توسط تستر'), ('FAILED', 'خاتمه ناموفقیت آمیز'), ('FINISH', 'خاتمه یافته')], default='DRAFTD', help_text='لطفاً کد وضعیت را وارد کنید.', max_length=6, verbose_name='کد وضعیت'),
        ),
        migrations.DeleteModel(
            name='ChangeType',
        ),
        migrations.DeleteModel(
            name='RequestCorp_ChangeType',
        ),
        migrations.DeleteModel(
            name='RequestTeam_ChangeType',
        ),
    ]
