# Generated by Django 5.0.12 on 2025-10-12 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ConfigurationChangeRequest', '0004_rename_change_type_requestextrainformation_changetype_changetype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='changetype',
            old_name='related_manager',
            new_name='related_manager_nationalcode',
        ),
    ]
