# Generated by Django 5.0.12 on 2025-02-28 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConfigurationChangeRequest', '0004_remove_configurationchangerequest_change_type_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_column='code', help_text='لطفاً کد نوع تغییر را وارد کنید.', max_length=6, verbose_name='کد نوع تغییر')),
                ('change_type_title', models.CharField(max_length=255, null=True, verbose_name='عنوان نوع تغییر')),
                ('change_title', models.CharField(help_text='لطفاً عنوان تغییر را وارد کنید.', max_length=255, verbose_name='عنوان تغییر')),
                ('change_description', models.TextField(blank=True, help_text='توضیحات مربوط به تغییر را وارد کنید.', max_length=1000, null=True, verbose_name='توضیحات تغییر')),
                ('change_location_data_center', models.BooleanField(default=False, help_text='آیا تغییر در مرکز داده انجام می\u200cشود؟', verbose_name='محل تغییر: مرکز داده')),
                ('change_location_database', models.BooleanField(default=False, help_text='آیا تغییر در پایگاه داده انجام می\u200cشود؟', verbose_name='محل تغییر: پایگاه داده')),
                ('change_location_systems', models.BooleanField(default=False, help_text='آیا تغییر در سیستم\u200cها انجام می\u200cشود؟', verbose_name='محل تغییر: سیستم\u200cها')),
                ('change_location_other', models.BooleanField(default=False, help_text='آیا تغییر در محل دیگری انجام می\u200cشود؟', verbose_name='محل تغییر: سایر')),
                ('change_location_other_description', models.CharField(blank=True, help_text='توضیحات مربوط به محل تغییر را وارد کنید.', max_length=500, null=True, verbose_name='توضیحات محل تغییر')),
                ('scope', models.CharField(choices=[('IN', 'درون سازمانی'), ('BOATH', 'بین سازمانی'), ('OUT', 'برون سازمانی')], help_text='لطفاً دامنه تغییر را انتخاب کنید.', max_length=6, verbose_name='دامنه تغییر')),
                ('changing_duration', models.DurationField(blank=True, help_text='مدت زمان تغییرات به ساعت و دقیقه.', null=True, verbose_name='مدت زمان تغییرات')),
                ('downtime_duration', models.DurationField(blank=True, help_text='مدت زمان توقف به ساعت و دقیقه.', null=True, verbose_name='مدت زمان توقف')),
                ('stop_critical_service', models.BooleanField(default=False, help_text='آیا خدمات بحرانی متوقف می\u200cشود؟', verbose_name='توقف خدمات بحرانی')),
                ('critical_service_title', models.CharField(blank=True, help_text='عنوان خدمات بحرانی را وارد کنید.', max_length=200, null=True, verbose_name='عنوان خدمات بحرانی')),
                ('stop_sensitive_service', models.BooleanField(default=False, help_text='آیا خدمات حساس متوقف می\u200cشود؟', verbose_name='توقف خدمات حساس')),
                ('stop_service_title', models.CharField(blank=True, help_text='عنوان خدمات متوقف شده را وارد کنید.', max_length=200, null=True, verbose_name='عنوان خدمات متوقف شده')),
                ('not_stop_any_service', models.BooleanField(default=False, help_text='آیا هیچ خدماتی متوقف نمی\u200cشود؟', verbose_name='عدم توقف هیچ خدماتی')),
                ('has_role_back_plan', models.BooleanField(default=False, help_text='آیا برنامه بازگشت وجود دارد؟', verbose_name='برنامه بازگشت وجود دارد')),
                ('role_back_plan_description', models.CharField(blank=True, help_text='توضیحات مربوط به برنامه بازگشت را وارد کنید.', max_length=1000, null=True, verbose_name='توضیحات برنامه بازگشت')),
                ('reason_regulatory', models.BooleanField(default=False, help_text='آیا الزام قانونی وجود دارد؟', verbose_name='الزام قانونی')),
                ('reason_technical', models.BooleanField(default=False, help_text='آیا الزام فنی وجود دارد؟', verbose_name='الزام فنی')),
                ('reason_security', models.BooleanField(default=False, help_text='آیا الزام امنیتی وجود دارد؟', verbose_name='الزام امنیتی')),
                ('reason_business', models.BooleanField(default=False, help_text='آیا الزام کسب و کاری وجود دارد؟', verbose_name='الزام کسب و کاری')),
                ('reason_other', models.BooleanField(default=False, help_text='آیا الزامات دیگری وجود دارد؟', verbose_name='سایر الزامات')),
                ('reason_other_description', models.CharField(blank=True, help_text='توضیحات مربوط به الزامات دیگر را وارد کنید.', max_length=500, null=True, verbose_name='توضیحات الزامات دیگر')),
                ('need_committee', models.BooleanField(default=False, help_text='آیا نیاز به کمیته وجود دارد؟', verbose_name='نیاز به کمیته')),
                ('test_required', models.BooleanField(default=0, help_text='در صورتی که نیاز به تست داشته باشد مقدار یک و در غیر این صورت مقدار صفر خواهد داشت', verbose_name='نیازمند تست است؟')),
                ('classification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ConfigurationChangeRequest.constvalue', verbose_name='طبقه\u200cبندی')),
                ('committee_user_nationalcode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='committee_users', to='ConfigurationChangeRequest.user', verbose_name='کد ملی کاربر کمیته')),
                ('executor_nationalcode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='executors', to='ConfigurationChangeRequest.user', verbose_name='کد ملی کاربر مجری')),
                ('manager_nationalcode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='managers', to='ConfigurationChangeRequest.user', verbose_name='کد ملی کاربر مدیر')),
                ('tester_nationalcode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='testers', to='ConfigurationChangeRequest.user', verbose_name='کد ملی کاربر تست کننده')),
            ],
            options={
                'verbose_name': 'نوع تغییر',
                'verbose_name_plural': 'انواع تغییرات',
                'db_table': 'change_type_table',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='configurationchangerequest',
            name='change_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ConfigurationChangeRequest.changetype', verbose_name='کد نوع تغییر'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='RequestCorp_ChangeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changetype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ConfigurationChangeRequest.changetype', verbose_name='کد نوع تغییر')),
                ('corp_code', models.ForeignKey(db_column='corp_code', on_delete=django.db.models.deletion.CASCADE, to='ConfigurationChangeRequest.corp', verbose_name='شرکت')),
            ],
            options={
                'verbose_name': 'شرکت در نوع درخواست',
                'verbose_name_plural': 'شرکت\u200cها در نوع  درخواست ها',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='RequestTeam_ChangeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changetype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ConfigurationChangeRequest.changetype', verbose_name='کد نوع تغییر')),
                ('team_code', models.ForeignKey(db_column='team_code', on_delete=django.db.models.deletion.CASCADE, to='ConfigurationChangeRequest.team', verbose_name='تیم')),
            ],
            options={
                'verbose_name': 'تیم بر اساس نوع درخواست',
                'verbose_name_plural': 'تیم\u200cها بر اساس نوع درخواست ها',
                'managed': True,
            },
        ),
    ]
