# Generated by Django 5.0.12 on 2025-09-17 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConfigurationChangeRequest', '0004_configurationchangerequest_create_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال است'),
        ),
    ]
