# Generated by Django 5.0.12 on 2025-09-17 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConfigurationChangeRequest', '0005_team_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestnotifygroup_changetype',
            name='request',
        ),
        migrations.AddField(
            model_name='requestnotifygroup',
            name='by_phone',
            field=models.BooleanField(default=False, verbose_name='اطلاع رسانی از طریق تلفن گویا'),
        ),
        migrations.AddField(
            model_name='requestnotifygroup_changetype',
            name='by_phone',
            field=models.BooleanField(default=False, verbose_name='اطلاع رسانی از طریق تلفن گویا'),
        ),
    ]
