# Generated by Django 5.0.12 on 2025-10-22 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConfigurationChangeRequest', '0005_rename_related_manager_changetype_related_manager_nationalcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestflow',
            name='user_role_code',
        ),
        migrations.AlterField(
            model_name='requestflow',
            name='user_role_id',
            field=models.ForeignKey(db_column='user_role_id', help_text='کد سمت کاربر', on_delete=django.db.models.deletion.CASCADE, related_name='user_role_id', to='ConfigurationChangeRequest.constvalue', verbose_name='کد سمت کاربر'),
        ),
    ]
