# Generated by Django 5.0.12 on 2025-02-28 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ConfigurationChangeRequest', '0005_changetype_configurationchangerequest_change_type_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='changetype',
            table=None,
        ),
    ]
