# Generated by Django 5.0.12 on 2025-09-24 08:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConfigurationChangeRequest', '0006_remove_requestnotifygroup_changetype_request_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskuser',
            name='is_active',
            field=models.BooleanField(default=True, help_text='مشخص می کند که این کاربر برای این تسک فعال است یا خیر؟', verbose_name='فعال است؟'),
        ),
        migrations.AlterField(
            model_name='configurationchangerequest',
            name='status_code',
            field=models.CharField(choices=[('DRAFTD', 'پیش نویس'), ('DIRMAN', 'اظهار نظر مدیر مستقیم'), ('RELMAN', 'اظهار نظر مدیر مربوطه'), ('COMITE', 'اظهار نظر کمیته'), ('DOTASK', 'انجام تسک ها'), ('FINISH', 'خاتمه یافته'), ('FAILED', 'خاتمه ناموفقیت آمیز'), ('ERRORF', 'خاتمه با خطا')], default='DRAFTD', help_text='لطفاً کد وضعیت را وارد کنید.', max_length=6, verbose_name='کد وضعیت'),
        ),
        migrations.AlterField(
            model_name='userteamrole',
            name='role_id',
            field=models.ForeignKey(db_column='role_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='ConfigurationChangeRequest.role', verbose_name='شناسه سمت'),
        ),
    ]
