# Generated by Django 5.0.12 on 2025-02-28 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConfigurationChangeRequest', '0006_alter_changetype_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changetype',
            name='change_title',
            field=models.CharField(help_text='لطفاً عنوان تغییر را وارد کنید.', max_length=255, null=True, verbose_name='عنوان تغییر'),
        ),
        migrations.AlterField(
            model_name='changetype',
            name='change_type_title',
            field=models.CharField(default=1, max_length=255, verbose_name='عنوان نوع تغییر'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='changetype',
            name='classification',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ConfigurationChangeRequest.constvalue', verbose_name='طبقه\u200cبندی'),
        ),
        migrations.AlterField(
            model_name='changetype',
            name='code',
            field=models.CharField(db_column='code', help_text='لطفاً کد نوع تغییر را وارد کنید.', max_length=6, null=True, verbose_name='کد نوع تغییر'),
        ),
        migrations.AlterField(
            model_name='changetype',
            name='committee_user_nationalcode',
            field=models.ForeignKey(blank=True, db_column='committee_user_nationalcode', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='committee_users', to='ConfigurationChangeRequest.user', verbose_name='کد ملی کاربر کمیته'),
        ),
        migrations.AlterField(
            model_name='changetype',
            name='executor_nationalcode',
            field=models.ForeignKey(blank=True, db_column='executor_nationalcode', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='executors', to='ConfigurationChangeRequest.user', verbose_name='کد ملی کاربر مجری'),
        ),
        migrations.AlterField(
            model_name='changetype',
            name='manager_nationalcode',
            field=models.ForeignKey(blank=True, db_column='manager_nationalcode', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='managers', to='ConfigurationChangeRequest.user', verbose_name='کد ملی کاربر مدیر'),
        ),
        migrations.AlterField(
            model_name='changetype',
            name='scope',
            field=models.CharField(choices=[('IN', 'درون سازمانی'), ('BOATH', 'بین سازمانی'), ('OUT', 'برون سازمانی')], help_text='لطفاً دامنه تغییر را انتخاب کنید.', max_length=6, null=True, verbose_name='دامنه تغییر'),
        ),
        migrations.AlterField(
            model_name='changetype',
            name='tester_nationalcode',
            field=models.ForeignKey(blank=True, db_column='tester_nationalcode', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='testers', to='ConfigurationChangeRequest.user', verbose_name='کد ملی کاربر تست کننده'),
        ),
    ]
