# Generated by Django 5.0.12 on 2025-10-22 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ConfigurationChangeRequest', '0006_remove_requestflow_user_role_code_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requestflow',
            old_name='receiver_date',
            new_name='receive_date',
        ),
    ]
