# Generated by Django 5.0.12 on 2025-10-22 21:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConfigurationChangeRequest', '0007_rename_receiver_date_requestflow_receive_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestflow',
            name='receive_date',
        ),
        migrations.RemoveField(
            model_name='requestflow',
            name='user_send_date',
        ),
        migrations.RemoveField(
            model_name='requestflow',
            name='user_send_time',
        ),
        migrations.AddField(
            model_name='requestflow',
            name='status_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='status_code', to='ConfigurationChangeRequest.constvalue', verbose_name='وضعیت درخواست'),
        ),
    ]
