# Generated by Django 5.0.12 on 2025-02-28 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConfigurationChangeRequest', '0007_alter_changetype_change_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changetype',
            name='change_type_title',
            field=models.CharField(max_length=255, null=True, verbose_name='عنوان نوع تغییر'),
        ),
    ]
