# Generated by Django 5.0.12 on 2025-09-24 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConfigurationChangeRequest', '0007_taskuser_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configurationchangerequest',
            name='related_manager_nationalcode',
            field=models.ForeignKey(db_column='related_manager_nationalcode', on_delete=django.db.models.deletion.CASCADE, related_name='related_manager_nationalcode', to='ConfigurationChangeRequest.user', verbose_name='کد ملی مدیر مربوطه'),
        ),
    ]
