# Generated by Django 5.0.12 on 2025-09-25 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConfigurationChangeRequest', '0008_alter_configurationchangerequest_related_manager_nationalcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='requesttask',
            name='order_number',
            field=models.PositiveSmallIntegerField(default=0, help_text='ترتیب اجرای تسک در درخواست را مشخص می کند', verbose_name='شماره ترتیب'),
        ),
        migrations.AddField(
            model_name='requesttask_changetype',
            name='order_number',
            field=models.PositiveSmallIntegerField(default=0, help_text='ترتیب اجرای تسک در نوع درخواست را مشخص می کند', verbose_name='شماره ترتیب'),
        ),
    ]
