# Generated by Django 5.0.12 on 2025-10-22 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConfigurationChangeRequest', '0008_remove_requestflow_receive_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestflow',
            name='status_code',
            field=models.CharField(choices=[('DRAFTD', 'پیش نویس'), ('DIRMAN', 'اظهار نظر مدیر مستقیم'), ('RELMAN', 'اظهار نظر مدیر مربوطه'), ('COMITE', 'اظهار نظر کمیته'), ('DOTASK', 'انجام تسک ها'), ('FINISH', 'خاتمه یافته'), ('FAILED', 'خاتمه ناموفقیت آمیز'), ('ERRORF', 'خاتمه با خطا')], default='DRAFTD', help_text='لطفاً کد وضعیت را وارد کنید.', max_length=6, verbose_name='کد وضعیت'),
        ),
    ]
