# Generated by Django 5.0.12 on 2025-02-28 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConfigurationChangeRequest', '0008_alter_changetype_change_type_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changetype',
            name='change_location_data_center',
            field=models.BooleanField(default=False, help_text='آیا تغییر در مرکز داده انجام می\u200cشود؟', null=True, verbose_name='محل تغییر: مرکز داده'),
        ),
        migrations.AlterField(
            model_name='changetype',
            name='change_location_database',
            field=models.BooleanField(default=False, help_text='آیا تغییر در پایگاه داده انجام می\u200cشود؟', null=True, verbose_name='محل تغییر: پایگاه داده'),
        ),
        migrations.AlterField(
            model_name='changetype',
            name='change_location_other',
            field=models.BooleanField(default=False, help_text='آیا تغییر در محل دیگری انجام می\u200cشود؟', null=True, verbose_name='محل تغییر: سایر'),
        ),
        migrations.AlterField(
            model_name='changetype',
            name='change_location_systems',
            field=models.BooleanField(default=False, help_text='آیا تغییر در سیستم\u200cها انجام می\u200cشود؟', null=True, verbose_name='محل تغییر: سیستم\u200cها'),
        ),
        migrations.AlterField(
            model_name='changetype',
            name='need_committee',
            field=models.BooleanField(default=False, help_text='آیا نیاز به کمیته وجود دارد؟', null=True, verbose_name='نیاز به کمیته'),
        ),
        migrations.AlterField(
            model_name='changetype',
            name='not_stop_any_service',
            field=models.BooleanField(default=False, help_text='آیا هیچ خدماتی متوقف نمی\u200cشود؟', null=True, verbose_name='عدم توقف هیچ خدماتی'),
        ),
        migrations.AlterField(
            model_name='changetype',
            name='reason_business',
            field=models.BooleanField(default=False, help_text='آیا الزام کسب و کاری وجود دارد؟', null=True, verbose_name='الزام کسب و کاری'),
        ),
        migrations.AlterField(
            model_name='changetype',
            name='reason_other',
            field=models.BooleanField(default=False, help_text='آیا الزامات دیگری وجود دارد؟', null=True, verbose_name='سایر الزامات'),
        ),
        migrations.AlterField(
            model_name='changetype',
            name='reason_regulatory',
            field=models.BooleanField(default=False, help_text='آیا الزام قانونی وجود دارد؟', null=True, verbose_name='الزام قانونی'),
        ),
        migrations.AlterField(
            model_name='changetype',
            name='reason_security',
            field=models.BooleanField(default=False, help_text='آیا الزام امنیتی وجود دارد؟', null=True, verbose_name='الزام امنیتی'),
        ),
        migrations.AlterField(
            model_name='changetype',
            name='reason_technical',
            field=models.BooleanField(default=False, help_text='آیا الزام فنی وجود دارد؟', null=True, verbose_name='الزام فنی'),
        ),
        migrations.AlterField(
            model_name='changetype',
            name='stop_critical_service',
            field=models.BooleanField(default=False, help_text='آیا خدمات بحرانی متوقف می\u200cشود؟', null=True, verbose_name='توقف خدمات بحرانی'),
        ),
        migrations.AlterField(
            model_name='changetype',
            name='stop_sensitive_service',
            field=models.BooleanField(default=False, help_text='آیا خدمات حساس متوقف می\u200cشود؟', null=True, verbose_name='توقف خدمات حساس'),
        ),
        migrations.AlterField(
            model_name='changetype',
            name='test_required',
            field=models.BooleanField(default=False, help_text='در صورتی که نیاز به تست داشته باشد مقدار یک و در غیر این صورت مقدار صفر خواهد داشت', null=True, verbose_name='نیازمند تست است؟'),
        ),
    ]
