# Generated by Django 5.0.12 on 2025-09-26 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConfigurationChangeRequest', '0009_requesttask_order_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notifygroupuser',
            old_name='notify_group_code',
            new_name='notify_group',
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('modify_date', models.DateTimeField(auto_now=True, verbose_name='تاریخ آخرین تغییر')),
                ('request_status', models.CharField(max_length=100, verbose_name='وضعیت فعلی درخواست')),
                ('task_status', models.CharField(max_length=100, verbose_name='وضعیت فعلی تسک')),
                ('template_code', models.CharField(max_length=20, verbose_name='کد الگوی اطلاع رسانی')),
                ('email_to', models.CharField(max_length=1000, null=True, verbose_name='آدرس ایمیل دریافت کنندگان To')),
                ('email_cc', models.CharField(max_length=1000, null=True, verbose_name='آدرس ایمیل دریافت کنندگان To')),
                ('email_bcc', models.CharField(max_length=1000, null=True, verbose_name='آدرس ایمیل دریافت کنندگان To')),
                ('variables', models.CharField(max_length=2000, null=True, verbose_name='متغییرها و مقادیر')),
                ('service_data', models.CharField(max_length=4000, null=True, verbose_name='مقادیر بازگشتی تابع')),
                ('service_return_val', models.SmallIntegerField(null=True, verbose_name='کد بازگشتی تابع')),
                ('creator_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)ss', to='ConfigurationChangeRequest.user', verbose_name='کاربر ایجادکننده')),
                ('last_modifier_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_%(class)ss', to='ConfigurationChangeRequest.user', verbose_name='آخرین کاربر ویرایشگر')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ConfigurationChangeRequest.configurationchangerequest', verbose_name='درخواست مربوطه')),
            ],
            options={
                'verbose_name': 'سابقه اطلاع رسانی',
                'verbose_name_plural': 'سوابق اطلاع رسانی ها',
            },
        ),
    ]
