# Generated by Django 5.0.12 on 2025-02-28 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConfigurationChangeRequest', '0009_alter_changetype_change_location_data_center_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changetype',
            name='has_role_back_plan',
            field=models.BooleanField(default=False, help_text='آیا برنامه بازگشت وجود دارد؟', null=True, verbose_name='برنامه بازگشت وجود دارد'),
        ),
    ]
