# Generated by Django 5.0.12 on 2025-10-22 21:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConfigurationChangeRequest', '0009_alter_requestflow_status_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestflow',
            name='user_role_id',
            field=models.ForeignKey(db_column='user_role_id', help_text='لطفاً سمت فرد کاربر را وارد کنید.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='ConfigurationChangeRequest.role', verbose_name='سمت کاربر'),
        ),
    ]
