# Generated by Django 5.0.12 on 2025-09-29 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConfigurationChangeRequest', '0010_rename_notify_group_code_notifygroupuser_notify_group_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configurationchangerequest',
            name='change_location_systems',
        ),
        migrations.AddField(
            model_name='configurationchangerequest',
            name='change_location_system_services',
            field=models.BooleanField(default=False, help_text='آیا تغییر در سیستم\u200cها و سرویس ها انجام می\u200cشود؟', verbose_name='محل تغییر: سیستم\u200cها و سرویس ها'),
        ),
    ]
