# Generated by Django 5.0.12 on 2025-03-02 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConfigurationChangeRequest', '0010_alter_changetype_has_role_back_plan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='configurationchangerequest',
            old_name='state_code',
            new_name='status_code',
        ),
        migrations.RemoveField(
            model_name='changetype',
            name='scope',
        ),
        migrations.RemoveField(
            model_name='configurationchangerequest',
            name='scope',
        ),
        migrations.AddField(
            model_name='changetype',
            name='change_domain',
            field=models.ForeignKey(help_text='دامنه تغییرات می تواند درون سازمانی، برون سازمانی و یا بین سازمانی باشد.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='change_domain', to='ConfigurationChangeRequest.constvalue', verbose_name='دامنه تغییر'),
        ),
        migrations.AddField(
            model_name='changetype',
            name='change_level',
            field=models.ForeignKey(help_text='تغییرات می تواند جزئی، بخشی و یا کلان باشد.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='change_level', to='ConfigurationChangeRequest.constvalue', verbose_name='گستردگی تغییرات'),
        ),
        migrations.AddField(
            model_name='changetype',
            name='priority',
            field=models.ForeignKey(help_text='اولویت می تواند استاندارد، فوری و اضطراری باشد.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='priority', to='ConfigurationChangeRequest.constvalue', verbose_name='اولویت'),
        ),
        migrations.AddField(
            model_name='changetype',
            name='risk_level',
            field=models.ForeignKey(help_text='سطح ریسک می تواند بالا، متوسط و پایین باشد.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='risk_level', to='ConfigurationChangeRequest.constvalue', verbose_name='سطح ریسک'),
        ),
        migrations.AddField(
            model_name='configurationchangerequest',
            name='change_domain',
            field=models.ForeignKey(help_text='دامنه تغییرات می تواند درون سازمانی، برون سازمانی و یا بین سازمانی باشد.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='request_change_domain', to='ConfigurationChangeRequest.constvalue', verbose_name='دامنه تغییر'),
        ),
        migrations.AddField(
            model_name='configurationchangerequest',
            name='change_level',
            field=models.ForeignKey(help_text='تغییرات می تواند جزئی، بخشی و یا کلان باشد.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='request_change_level', to='ConfigurationChangeRequest.constvalue', verbose_name='گستردگی تغییرات'),
        ),
        migrations.AddField(
            model_name='configurationchangerequest',
            name='priority',
            field=models.ForeignKey(help_text='اولویت می تواند استاندارد، فوری و اضطراری باشد.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='request_priority', to='ConfigurationChangeRequest.constvalue', verbose_name='اولویت'),
        ),
        migrations.AddField(
            model_name='configurationchangerequest',
            name='risk_level',
            field=models.ForeignKey(help_text='سطح ریسک می تواند بالا، متوسط و پایین باشد.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='request_risk_level', to='ConfigurationChangeRequest.constvalue', verbose_name='سطح ریسک'),
        ),
        migrations.AlterField(
            model_name='changetype',
            name='classification',
            field=models.ForeignKey(help_text='طبقه\u200cبندی می تواند عادی یا محرمانه باشد.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classification', to='ConfigurationChangeRequest.constvalue', verbose_name='طبقه\u200cبندی'),
        ),
        migrations.AlterField(
            model_name='changetype',
            name='critical_service_title',
            field=models.CharField(blank=True, help_text='عنوان خدمات بحرانی را وارد کنید.', max_length=50, null=True, verbose_name='خدمات بحرانی'),
        ),
        migrations.AlterField(
            model_name='configurationchangerequest',
            name='classification',
            field=models.ForeignKey(help_text='طبقه\u200cبندی می تواند عادی یا محرمانه باشد.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='request_classification', to='ConfigurationChangeRequest.constvalue', verbose_name='طبقه\u200cبندی'),
        ),
    ]
