# Generated by Django 5.0.12 on 2025-10-24 07:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConfigurationChangeRequest', '0010_alter_requestflow_user_role_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestflow',
            name='reqeust_task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ConfigurationChangeRequest.requesttask', verbose_name='شناسه تسک درخواست'),
        ),
    ]
