# Generated by Django 5.0.12 on 2025-09-29 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConfigurationChangeRequest', '0011_remove_configurationchangerequest_change_location_systems_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='changetype',
            name='change_location_systems',
        ),
        migrations.AddField(
            model_name='changetype',
            name='change_location_system_services',
            field=models.BooleanField(default=False, help_text='آیا تغییر در سیستم\u200cها یا سرویس ها انجام می\u200cشود؟', null=True, verbose_name='محل تغییر: سیستم\u200cها و سرویس ها'),
        ),
    ]
