# Generated by Django 5.0.12 on 2025-10-24 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConfigurationChangeRequest', '0011_requestflow_reqeust_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datahistory',
            name='new_data',
            field=models.TextField(null=True, verbose_name='اطلاعات جدید'),
        ),
        migrations.AlterField(
            model_name='datahistory',
            name='old_data',
            field=models.TextField(null=True, verbose_name='اطلاعات قدیمی'),
        ),
    ]
