# Generated by Django 5.0.12 on 2025-03-02 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ConfigurationChangeRequest', '0011_rename_state_code_configurationchangerequest_status_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='changetype',
            name='manager_nationalcode',
        ),
    ]
