# Generated by Django 5.0.12 on 2025-10-24 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConfigurationChangeRequest', '0012_alter_datahistory_new_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requesttask',
            name='doc_id',
            field=models.PositiveIntegerField(null=True, verbose_name='شناسه سند'),
        ),
    ]
