# Generated by Django 5.0.12 on 2025-09-29 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConfigurationChangeRequest', '0012_remove_changetype_change_location_systems_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskuserselected',
            name='request_task',
        ),
        migrations.RemoveField(
            model_name='taskuserselected',
            name='task_user',
        ),
        migrations.AddField(
            model_name='taskuserselected',
            name='request_task_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ConfigurationChangeRequest.requesttaskuser', verbose_name='شناسه کاربر تسک'),
            preserve_default=False,
        ),
    ]
