# Generated by Django 5.0.12 on 2025-03-12 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConfigurationChangeRequest', '0012_remove_changetype_manager_nationalcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Committee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='عنوان کمیته')),
                ('administrator_nationalCode', models.CharField(max_length=10, verbose_name='کد ملی دبیر کمیته')),
                ('is_active', models.BooleanField(default=True, verbose_name='کمیته فعال است؟')),
            ],
            options={
                'verbose_name': 'کمیته',
                'verbose_name_plural': 'کمیته ها',
            },
        ),
        migrations.RemoveField(
            model_name='changetype',
            name='committee_user_nationalcode',
        ),
        migrations.AddField(
            model_name='changetype',
            name='committee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ConfigurationChangeRequest.committee', verbose_name='کمیته'),
        ),
        migrations.AddField(
            model_name='configurationchangerequest',
            name='committee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ConfigurationChangeRequest.committee', verbose_name='کمیته'),
        ),
    ]
