# Generated by Django 5.0.12 on 2025-03-12 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ConfigurationChangeRequest', '0013_committee_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configurationchangerequest',
            name='committee',
        ),
        migrations.RemoveField(
            model_name='changetype',
            name='committee',
        ),
        migrations.DeleteModel(
            name='Committee',
        ),
    ]
