# Generated by Django 5.0.12 on 2025-09-29 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ConfigurationChangeRequest', '0013_remove_taskuserselected_request_task_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TaskUserSelected',
            new_name='RequestTaskUserSelected',
        ),
    ]
