# Generated by Django 5.0.12 on 2025-11-04 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ConfigurationChangeRequest', '0013_requesttask_doc_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requestflow',
            old_name='reqeust_task',
            new_name='request_task',
        ),
    ]
