# Generated by Django 5.0.12 on 2026-01-29 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConfigurationChangeRequest', '0014_rename_reqeust_task_requestflow_request_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationlog',
            name='email_bcc',
            field=models.CharField(max_length=1000, null=True, verbose_name='آدرس ایمیل دریافت کنندگان BCC'),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='email_cc',
            field=models.CharField(max_length=1000, null=True, verbose_name='آدرس ایمیل دریافت کنندگان CC'),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='email_to',
            field=models.CharField(max_length=4000, null=True, verbose_name='آدرس ایمیل دریافت کنندگان To'),
        ),
    ]
