# Generated by Django 5.0.12 on 2025-03-18 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConfigurationChangeRequest', '0016_alter_committee_administrator_nationalcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestExtraInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ExtraInfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ConfigurationChangeRequest.constvalue', verbose_name='شناسه اطلاعات تکمیلی')),
                ('Request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ConfigurationChangeRequest.configurationchangerequest', verbose_name='شناسه درخواست')),
            ],
            options={
                'verbose_name': 'اطلاعات تکمیلی درخواست',
                'verbose_name_plural': 'اطلاعات تکمیلی درخواست\u200cها',
            },
        ),
        migrations.CreateModel(
            name='RequestExtraInformation_ChangeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ExtraInfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ConfigurationChangeRequest.constvalue', verbose_name='شناسه اطلاعات تکمیلی')),
                ('Request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ConfigurationChangeRequest.changetype', verbose_name='شناسه نوع درخواست')),
            ],
            options={
                'verbose_name': 'اطلاعات تکمیلی درخواست',
                'verbose_name_plural': 'اطلاعات تکمیلی درخواست\u200cها',
            },
        ),
    ]
