# Generated by Django 5.0.12 on 2025-03-18 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConfigurationChangeRequest', '0017_requestextrainformation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corp',
            name='corp_code',
            field=models.CharField(help_text='کد منحصر به فرد شرکت را وارد کنید.', max_length=3, primary_key=True, serialize=False, verbose_name='کد شرکت'),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_code',
            field=models.CharField(help_text='کد منحصر به فرد تیم را وارد کنید.', max_length=3, primary_key=True, serialize=False, verbose_name='کد تیم'),
        ),
    ]
