# Generated by Django 5.0.12 on 2025-03-18 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ConfigurationChangeRequest', '0018_alter_corp_corp_code_alter_team_team_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requestextrainformation_changetype',
            old_name='Request',
            new_name='ChangeType',
        ),
    ]
