# Generated by Django 5.0.12 on 2025-03-18 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ConfigurationChangeRequest', '0019_rename_request_requestextrainformation_changetype_changetype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requestextrainformation',
            old_name='ExtraInfo',
            new_name='extra_info',
        ),
        migrations.RenameField(
            model_name='requestextrainformation',
            old_name='Request',
            new_name='request',
        ),
        migrations.RenameField(
            model_name='requestextrainformation_changetype',
            old_name='ChangeType',
            new_name='change_type',
        ),
        migrations.RenameField(
            model_name='requestextrainformation_changetype',
            old_name='ExtraInfo',
            new_name='extra_info',
        ),
    ]
