# Generated by Django 5.0.12 on 2025-04-17 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConfigurationChangeRequest', '0020_rename_extrainfo_requestextrainformation_extra_info_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='changetype',
            name='downtime_duration_worsecase',
            field=models.PositiveIntegerField(blank=True, help_text='مدت زمان توقف بر حسب دقیقه.', null=True, verbose_name='بدترین مدت زمان توقف'),
        ),
        migrations.AddField(
            model_name='configurationchangerequest',
            name='downtime_duration_worsecase',
            field=models.PositiveIntegerField(blank=True, help_text='بدترین مدت زمان توقف به دقیقه.', null=True, verbose_name='بدترین مدت زمان توقف'),
        ),
        migrations.AlterField(
            model_name='changetype',
            name='changing_duration',
            field=models.PositiveIntegerField(blank=True, help_text='مدت زمان تغییرات بر حسب دقیقه.', null=True, verbose_name='مدت زمان تغییرات'),
        ),
        migrations.AlterField(
            model_name='changetype',
            name='downtime_duration',
            field=models.PositiveIntegerField(blank=True, help_text='مدت زمان توقف بر حسب دقیقه.', null=True, verbose_name='مدت زمان توقف'),
        ),
        migrations.AlterField(
            model_name='configurationchangerequest',
            name='changing_duration',
            field=models.PositiveIntegerField(blank=True, help_text='مدت زمان تغییرات به دقیقه.', null=True, verbose_name='مدت زمان تغییرات'),
        ),
        migrations.AlterField(
            model_name='configurationchangerequest',
            name='changing_duration_actual',
            field=models.PositiveIntegerField(blank=True, help_text='مدت زمان واقعی تغییرات به دقیقه.', null=True, verbose_name='مدت زمان واقعی تغییرات'),
        ),
        migrations.AlterField(
            model_name='configurationchangerequest',
            name='downtime_duration',
            field=models.PositiveIntegerField(blank=True, help_text='مدت زمان توقف به دقیقه.', null=True, verbose_name='مدت زمان توقف'),
        ),
        migrations.AlterField(
            model_name='configurationchangerequest',
            name='downtime_duration_actual',
            field=models.PositiveIntegerField(blank=True, help_text='مدت زمان توقف واقعی به دقیقه.', null=True, verbose_name='مدت زمان توقف واقعی'),
        ),
    ]
