# Generated by Django 5.0.12 on 2025-04-21 21:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConfigurationChangeRequest', '0022_rename_downtime_duration_worsecase_changetype_downtime_duration_worstcase_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configurationchangerequest',
            name='requestor_role_title',
        ),
        migrations.AddField(
            model_name='configurationchangerequest',
            name='executor_role_id',
            field=models.PositiveIntegerField(default=-1, help_text='لطفاً سمت فرد مجری را وارد کنید.', verbose_name='سمت مجری'),
        ),
        migrations.AddField(
            model_name='configurationchangerequest',
            name='executor_team_code',
            field=models.ForeignKey(blank=True, db_column='executor_team_code', help_text='تیم مربوط به مجری را انتخاب کنید.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executor_team_code', to='ConfigurationChangeRequest.team', verbose_name='تیم مجری'),
        ),
        migrations.AddField(
            model_name='configurationchangerequest',
            name='requestor_role_id',
            field=models.PositiveIntegerField(default=-1, help_text='لطفاً سمت فرد درخواست\u200cدهنده را وارد کنید.', verbose_name='سمت درخواست\u200cدهنده'),
        ),
        migrations.AddField(
            model_name='configurationchangerequest',
            name='tester_role_id',
            field=models.PositiveIntegerField(default=-1, help_text='لطفاً سمت فرد تستر را وارد کنید.', verbose_name='سمت تستر'),
        ),
        migrations.AddField(
            model_name='configurationchangerequest',
            name='tester_team_code',
            field=models.ForeignKey(blank=True, db_column='tester_team_code', help_text='تیم مربوط به تستر را انتخاب کنید.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tester_team_code', to='ConfigurationChangeRequest.team', verbose_name='تیم تستر'),
        ),
        migrations.AddField(
            model_name='userteamrole',
            name='role_id',
            field=models.IntegerField(default=-1, verbose_name='شناسه سمت'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='configurationchangerequest',
            name='status_code',
            field=models.CharField(choices=[('DRAFTD', 'پیش نویس'), ('MANAGE', 'اظهار نظر مدیر مستقیم'), ('COMITE', 'اظهار نظر کمیته'), ('EXECUT', 'اجرا توسط مجری'), ('TESTER', 'تست توسط تستر'), ('FINISH', 'خاتمه یافته'), ('FAILED', 'خاتمه ناموفقیت آمیز')], default='DRAFTD', help_text='لطفاً کد وضعیت را وارد کنید.', max_length=6, verbose_name='کد وضعیت'),
        ),
    ]
