# Generated by Django 5.0.12 on 2025-04-24 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConfigurationChangeRequest', '0026_alter_configurationchangerequest_changing_date_actual_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.BooleanField(default=True, help_text='در صورتی که مرد باشد مقدار صحیح و در غیر این صورت مقدار غلط خواهد داشت', verbose_name='جنسیت'),
        ),
    ]
