# Generated by Django 5.0.12 on 2025-04-24 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConfigurationChangeRequest', '0027_user_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('role_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='شناسه سمت')),
                ('role_title', models.CharField(max_length=150, verbose_name='عنوان سمت')),
            ],
            options={
                'verbose_name': 'سمت',
                'verbose_name_plural': 'سمت\u200cها',
                'managed': True,
            },
        ),
        migrations.AlterField(
            model_name='configurationchangerequest',
            name='executor_role_id',
            field=models.ForeignKey(db_column='executor_role_id', help_text='لطفاً سمت فرد مجری را وارد کنید.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executor_role_id', to='ConfigurationChangeRequest.role', verbose_name='سمت مجری'),
        ),
        migrations.AlterField(
            model_name='configurationchangerequest',
            name='requestor_role_id',
            field=models.ForeignKey(db_column='requestor_role_id', help_text='لطفاً سمت فرد درخواست\u200cدهنده را وارد کنید.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requestor_role_id', to='ConfigurationChangeRequest.role', verbose_name='سمت درخواست\u200cدهنده'),
        ),
        migrations.AlterField(
            model_name='configurationchangerequest',
            name='tester_role_id',
            field=models.ForeignKey(db_column='tester_role_id', help_text='لطفاً سمت فرد تستر را وارد کنید.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tester_role_id', to='ConfigurationChangeRequest.role', verbose_name='سمت تستر'),
        ),
    ]
